# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jd_U0fCzE8DIGAjhCW3ML6R7STtiQ3nb

Exercice 1 : Bonjour le monde
"""

print("Hello world\n" * 4, end="")

"""Exercice 2 : Un peu de maths"""

# Calcul et affichage du résultat
resultat = (99 ** 3) * 8
print(resultat)

"""Exercice 3 : Quel est le résultat ?"""

# 1
age = 18
if age >= 18:
    print("Majeur")
else:
    print("Mineur")

# 2
note = 85
if note >= 90:
    print("Excellent")
elif note >= 70:
    print("Bien")
elif note >= 50:
    print("Passable")
else:
    print("Insuffisant")

# 3
x = 10
if x > 5:
    print("A")
    if x > 8:
        print("B")
    else:
        print("C")

# 4
mot = "python"
if "y" in mot:
    print("Oui")
else:
    print("Non")

# 5
nombre = 7
if nombre % 2 == 0:
    print("Pair")
else:
    print("Impair")

# 6
valeur = "5"
if valeur == 5:
    print("Égal")
else:
    print("Différent")

""" Exercice 4 : Votre marque informatique"""

# Création de la variable avec la marque de l'ordinateur
computer_brand = "Apple"  # Vous pouvez remplacer "Apple" par "Dell", "HP", etc.

# Affichage de la phrase en utilisant la variable
print(f"I have a {computer_brand} computer.")

# Création de la variable
computer_brand = "Dell"   # ← Change ici avec ta vraie marque

# Affichage de la phrase
print("I have a " + computer_brand + " computer.")

computer_brand = "Apple"   # ← Modifie avec ta marque (ex: HP, Lenovo, Asus, etc.)

print(f"I have a {computer_brand} computer.")

"""Exercice 5 : Vos informations"""

# 1. Création des variables personnelles
name = "Alex"
age = 25
shoe_size = 42

# 2. Création de la phrase intéressante combinant toutes les variables
info = f"Je m'appelle {name}, j'ai {age} ans, je chausse du {shoe_size} et je peux coder en Python tout en fermant les yeux !"

# 3. Affichage du message
print(info)

# ========================
# Exercice 5 - Vos informations
# ========================

# 1. Création des variables
name = "Yao"                    # Remplace par ton vrai prénom/nom
age = 25                        # Remplace par ton âge réel
shoe_size = 42                  # Remplace par ta pointure

# 2. Création de la variable "info" avec une phrase intéressante
info = f"Je m'appelle {name}, j'ai {age} ans, je chausse du {shoe_size} et je suis en train d'apprendre Python à Abidjan !"

# 3. Affichage
print(info)
info = f"""
Bonjour, je m'appelle {name}.
J'ai actuellement {age} ans et je porte du {shoe_size} de pointure.
Je suis actuellement à Abidjan et j'apprends le langage Python.
"""

print(info)

"""Exercice 6 : A & B"""

# Création des variables
a = 20
b = 15

# Condition
if a > b:
    print("Hello World")

# Cas 1 : a plus grand
a = 30
b = 10
if a > b:
    print("Hello World")        # ← S'affiche

# Cas 2 : a plus petit
a = 5
b = 12
if a > b:
    print("Hello World")        # ← Ne s'affiche pas

# Cas 3 : a égal à b
a = 10
b = 10
if a > b:
    print("Hello World")        # ← Ne s'affiche pas (car ce n'est pas "plus grand")

# 1. Création des deux variables numériques
a = 15
b = 10

# 2. Structure conditionnelle pour comparer a et b
if a > b:
    print("Hello World")

"""Exercice 7 : Pair ou impair"""

# Demonstration de la logique pair/impair avec l'opérateur modulo

# Exemple 1: Nombre pair
number1 = 10
result1 = number1 % 2
status1 = "pair" if result1 == 0 else "impair"
print(f"{number1} % 2 = {result1} \u2192 {status1} ({number1} = 2 \u00d7 {number1 // 2}, reste {result1})")

# Exemple 2: Nombre impair
number2 = 7
result2 = number2 % 2
status2 = "pair" if result2 == 0 else "impair"
print(f"{number2} % 2 = {result2} \u2192 {status2} ({number2} = 2 \u00d7 {number2 // 2}, reste {result2})")

"""Exercice 8 : Comment tu t’appelles ?

## Comment installer des bibliothèques Python ?

Pour installer des bibliothèques Python, vous utilisez généralement `pip`, le gestionnaire de paquets par défaut pour Python. Voici la commande de base :

```bash
pip install nom_de_la_bibliothèque
```

Si vous souhaitez installer une version spécifique, vous pouvez le faire comme ceci :

```bash
pip install nom_de_la_bibliothèque==version_specifique
```

Si vous êtes dans un environnement Jupyter ou Colab, vous devez souvent préfixer la commande `pip` avec un point d'exclamation `!` pour l'exécuter comme une commande shell :

```python
!pip install nom_de_la_bibliothèque
```

Par exemple, pour installer la bibliothèque `requests` (souvent utilisée pour faire des requêtes HTTP) :
"""

# Exemple d'installation de la bibliothèque 'requests'
!pip install requests

# Vous pouvez ensuite importer et utiliser la bibliothèque
import requests
print('La bibliothèque requests est maintenant installée et peut être importée.')

"""Exercice 9 : Assez grand pour faire des montagnes russes
Instructions

"""